dataE <- read.table(file = "D:\\Data\\datosElec\\household_power_consumption.txt", header = TRUE, sep = ";", dec = ".")
head(dataE,10)
dim(dataE)
names(dataE)
ncol(dataE)
nrow(dataE)
summary(dataE)
library(dplyr)
dataDate <- select(dataE, Date:Global_active_power)
head(dataDate, 10)
class(dataDate$Date)
class(dataDate$Time)
library(tibble)
library(tidyr)
DataDate<- unite(dataDate, Date, Time, col = "Date/Time", sep = " ")
head(DataDate)
class(DataDate$`Date/Time`)
Data01 <- strptime(DataDate, format = "%Y-%m-%d %H:%M:%OS" )
